---
title: Menna Tollah Rafat
timezone: Africa/Cairo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: menna12rere@gmail.com
description: Personal blog and resume .
baseurl: 
url: http://Menna-Rafat.com
github_username: Menna-Rafat
markdown: kramdown
