---
title: Menna Tollah Rafat
timezone: Africa/Cairo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  liked-it:
    title: liked it
    output: true
email: menna12rere@gmail.com
description: Personal blog and resume .
baseurl: 
url: http://Menna-Rafat.com
github_username: Menna-Rafat
markdown: kramdown
linkedin: https://www.linkedin.com/in/menna-el-khatib-404826181/
